# Generated by Django 4.1.7 on 2023-02-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField()),
                ('dorp', models.TextField()),
                ('provinsie', models.TextField()),
                ('poskode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnommer', models.TextField(max_length=13)),
                ('title', models.TextField(choices=[('Mev.', 'Mev'), ('Mnr.', 'Mnr.'), ('Rev.', 'Rev.')])),
                ('vollename', models.TextField(max_length=500)),
                ('van', models.TextField(max_length=500)),
                ('noemnaam', models.TextField(max_length=500)),
                ('geboortedatum', models.DateField()),
                ('epos', models.EmailField(max_length=254)),
                ('geslag', models.TextField(choices=[('Manlik', 'Manlik'), ('Vroulik', 'Vroulik')])),
                ('huwelikstatus', models.TextField(choices=[('Ongetroud', 'Ongetroud'), ('Getroud', 'Getroud')])),
                ('huistaal', models.TextField()),
                ('ras', models.TextField()),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amok_profiel.adres')),
            ],
        ),
    ]
