# Generated by Django 4.1.7 on 2023-02-27 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amok_profiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='skepdatum',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='adres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amok_profiel.adres'),
        ),
    ]
