# Generated by Django 4.1.7 on 2023-02-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amok_profiel', '0002_profiel_skepdatum_alter_profiel_adres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresse'},
        ),
        migrations.AlterModelOptions(
            name='profiel',
            options={'verbose_name': 'Amok Profiel', 'verbose_name_plural': 'Amok Profiele'},
        ),
        migrations.AlterField(
            model_name='profiel',
            name='geslag',
            field=models.CharField(choices=[('Manlik', 'Manlik'), ('Vroulik', 'Vroulik')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='huistaal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='huwelikstatus',
            field=models.CharField(choices=[('Ongetroud', 'Ongetroud'), ('Getroud', 'Getroud')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='idnommer',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='noemnaam',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='ras',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='title',
            field=models.CharField(choices=[('Mev.', 'Mev'), ('Mnr.', 'Mnr.'), ('Rev.', 'Rev.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='van',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='vollename',
            field=models.CharField(max_length=500),
        ),
    ]
