# Generated by Django 4.1.7 on 2023-02-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amok_profiel', '0003_alter_adres_options_alter_profiel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='voertuig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrikaat', models.CharField(max_length=300)),
                ('reeks', models.CharField(max_length=300)),
                ('kleur', models.CharField(max_length=50)),
                ('jaar_model', models.CharField(max_length=50)),
                ('registrasie', models.CharField(max_length=10)),
                ('nota', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'Voertuig',
                'verbose_name_plural': 'Voertuie',
            },
        ),
        migrations.AlterField(
            model_name='adres',
            name='dorp',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='adres',
            name='provinsie',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='adres',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amok_profiel.adres'),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='geslag',
            field=models.CharField(choices=[('Manlik', 'Manlik'), ('Vroulik', 'Vroulik')], default='Manlik', max_length=10),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='huwelikstatus',
            field=models.CharField(choices=[('Ongetroud', 'Ongetroud'), ('Getroud', 'Getroud')], default='Getroud', max_length=10),
        ),
    ]
