# Generated by Django 4.1.7 on 2023-02-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amok_profiel', '0004_voertuig_alter_adres_dorp_alter_adres_provinsie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='foto',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
